name: Publish NPM package

on:
  push:
    tags:
    - v*

env:
  MAIN_BRANCH: main

jobs:
  publish:
    name: Publish NPM package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com

    - name: Update version
      id: bump
      run: |
        VERSION="${GITHUB_REF/refs\/tags\//}"
        npm version --no-git-tag-version --allow-same-version "$VERSION"

        echo ::set-output name=VERSION::${VERSION}

    - name: Install dependencies
      run: |
        npm ci

    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm publish --ignore-scripts

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: |
          Bump to ${{ steps.bump.outputs.VERSION }}
          [skip ci]
        push: origin HEAD:${{ env.MAIN_BRANCH }}
        tag: ${{ steps.bump.outputs.VERSION }} --force
        tag_push: --force
